<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SIL.Secrets</RootNamespace>
    <PackageId>hawkeye116477.PasswordStore</PackageId>
    <Description>hawkeye116477.PasswordStore implements a cross-platform keyring that allows to securely store passwords and other secrets
(forked from https://github.com/sillsdev/SIL.PasswordStore).</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <TargetFramework>net462</TargetFramework>
    <TargetFrameworks />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="/">
      <Link>README.md</Link>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <PathMap>$(MSBuildProjectDirectory)=Dev:/SIL.PasswordStore</PathMap>
    <PackageProjectUrl>https://github.com/hawkeye116477/hawkeye116477.PasswordStore</PackageProjectUrl>
    <AssemblyName>hawkeye116477.PasswordStore</AssemblyName>
    <Authors>hawkeye116477</Authors>
    <Company>hawkeye116477</Company>
  </PropertyGroup>
</Project>
