<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFramework>net462</TargetFramework>
    <TargetFrameworks />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIL.PasswordStore\SIL.PasswordStore.csproj" />
  </ItemGroup>

</Project>
